const memorySeedData = [
{description: "fun in Napa!",
image: "img.jpg",
},
{description: "fun in SF!",
image: "img.jpg",
},
{description: "fun in Denver!",
image: "img.jpg",
},
{description: "fun in Napa with friends!",
image: "img.jpg",
},
{description: "fun in Napa wine!",
image: "img.jpg",
},
{description: "fun in the snow!",
image: "img.jpg",
},
{description: "fun in the rain!",
image: "img.jpg",
grouping: "Denver 2022",
},
{description: "fun in the city!",
image: "img.jpg",
},
  ]

  module.exports = memorySeedData